FROM python:3.9-alpine

# TODO: what is this?
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt
# permanent dependencies
RUN apk add --update --no-cache postgresql-client jpeg-dev
# temporary dependencies
# TODO: what is \ for?
RUN apk add --update --no-cache --virtual .tmp-build-deps \
      gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev
RUN pip install -r /requirements.txt
RUN apk del .tmp-build-deps

# TODO: need this?
# RUN mkdir /app
WORKDIR /app
COPY . .

# store media files uploaded by users
RUN mkdir -p /vol/web/media
# store static files
RUN mkdir -p /vol/web/static

RUN adduser -D user
# change owner (of file system files, directories)
RUN chown -R user:user /vol/
# change mode (access permissions of file system objects)
RUN chmod -R 755 /vol/web
USER user
