# only used for testing
version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - PGHOST=db
      - PGDATABASE=digitalace_db
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=digitalace_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
