# Generated by Django 3.2.3 on 2021-05-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210527_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
            ],
        ),
    ]
