# Generated by Django 3.2.3 on 2021-05-28 07:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210528_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('payment_note', models.TextField(blank=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('payment_note', models.TextField(blank=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
