# Generated by Django 3.2.3 on 2021-05-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_invoiceitem_salesorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='invoice',
            new_name='sales_order',
        ),
    ]
