# Generated by Django 3.2.3 on 2021-05-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210528_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salesorder'),
        ),
        migrations.AddField(
            model_name='receive',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.purchaseorder'),
        ),
    ]
