# Generated by Django 3.2.3 on 2021-06-06 17:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210528_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@digitalace.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='first_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='receivables',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='default@digitalace.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payables',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
