# Generated by Django 3.2.3 on 2021-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210606_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
            preserve_default=False,
        ),
    ]
