# Generated by Django 3.2.3 on 2021-06-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_product_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='attention',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='attention',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='attention',
            new_name='agent',
        ),
    ]
