# Generated by Django 3.2.3 on 2021-06-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210608_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='attention',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='attention',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
