# Generated by Django 3.2.3 on 2021-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210608_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='area',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='area',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
