# Generated by Django 3.2.3 on 2021-06-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210608_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='status',
        ),
    ]
