# Generated by Django 3.2.3 on 2021-06-09 14:39

import core.models.maintenance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210609_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.maintenance.category_image_file_path),
        ),
    ]
