# Generated by Django 3.2.3 on 2021-06-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_productcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
    ]
