# Generated by Django 3.2.3 on 2021-06-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_user_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='agent',
            new_name='agents',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='agent',
            new_name='agents',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='agent',
            new_name='agents',
        ),
    ]
