# Generated by Django 3.2.3 on 2021-06-16 14:26

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.user.department_image_file_path),
        ),
        migrations.AddField(
            model_name='role',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.user.role_image_file_path),
        ),
    ]
