# Generated by Django 3.2.3 on 2021-06-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20210625_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='receiveitem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='cost',
        ),
    ]
