# Generated by Django 3.2.3 on 2021-06-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20210626_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfig',
        ),
    ]
