# Generated by Django 3.2.3 on 2021-06-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_supplier_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(default='P-0000', max_length=255),
            preserve_default=False,
        ),
    ]
