# Generated by Django 3.2.3 on 2021-07-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_invoice_credits_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salesorder'),
        ),
    ]
