# Generated by Django 3.2.3 on 2021-07-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_creditnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('credit_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.creditnote')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice')),
            ],
        ),
    ]
