# Generated by Django 3.2.3 on 2021-07-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_deliveryorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('mode', models.CharField(blank=True, choices=[('INC', 'Increase'), ('DEC', 'Decrease')], default='INC', max_length=3)),
                ('status', models.CharField(blank=True, choices=[('DFT', 'Draft'), ('ADJ', 'Adjusted')], default='DFT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
