# Generated by Django 3.2.3 on 2021-07-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_invoice_balance_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsapplication',
            name='credit_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.creditnote'),
        ),
        migrations.AlterField(
            model_name='creditsapplication',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.invoice'),
        ),
    ]
