# Generated by Django 3.2.3 on 2021-07-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20210707_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='mode',
            field=models.CharField(blank=True, choices=[('INC', 'Increase'), ('DEC', 'Decrease')], default='INC', max_length=4),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='status',
            field=models.CharField(blank=True, choices=[('DFT', 'Draft'), ('ADJ', 'Adjusted')], default='DFT', max_length=4),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(blank=True, choices=[('DFT', 'Draft'), ('OP', 'Open'), ('CL', 'Closed')], default='DFT', max_length=4),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('DFT', 'Draft'), ('PD', 'Paid'), ('UPD', 'Unpaid')], default='DFT', max_length=4),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('DFT', 'Draft'), ('CP', 'Completed'), ('PNDG', 'Pending'), ('CC', 'Cancelled')], default='DFT', max_length=4),
        ),
        migrations.AlterField(
            model_name='receive',
            name='status',
            field=models.CharField(blank=True, choices=[('DFT', 'Draft'), ('PD', 'Paid'), ('UPD', 'Unpaid')], default='DFT', max_length=4),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(blank=True, choices=[('DFT', 'Draft'), ('CP', 'Completed'), ('PNDG', 'Pending'), ('CC', 'Cancelled')], default='DFT', max_length=4),
        ),
    ]
