# Generated by Django 3.2.3 on 2021-07-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20210714_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='reference',
            field=models.CharField(default='ADJ-0000', max_length=255),
            preserve_default=False,
        ),
    ]
