# Generated by Django 3.2.3 on 2021-07-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_adjustment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
    ]
