# Generated by Django 3.2.3 on 2021-07-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_adjustment_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentitem',
            name='adjustment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.adjustment'),
            preserve_default=False,
        ),
    ]
