# Generated by Django 3.2.3 on 2021-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('DFT', 'Draft'), ('OP', 'Open')], default='DFT', max_length=4)),
                ('severity', models.CharField(blank=True, choices=[('SUCC', 'Success'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERR', 'Error')], default='INFO', max_length=4)),
            ],
        ),
    ]
