name: Run CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: pip install docker-compose

      - name: Run CI
        run: docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8 --ignore=E501,F401,F403,F405,W503"
